// Generated by gencpp from file robot_msgs/Move.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_MOVE_H
#define ROBOT_MSGS_MESSAGE_MOVE_H

#include <ros/service_traits.h>


#include <robot_msgs/MoveRequest.h>
#include <robot_msgs/MoveResponse.h>


namespace robot_msgs
{

struct Move
{

typedef MoveRequest Request;
typedef MoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Move
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::Move > {
  static const char* value()
  {
    return "1b38d8d2cdd7e17ee1138874afabea4f";
  }

  static const char* value(const ::robot_msgs::Move&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::Move > {
  static const char* value()
  {
    return "robot_msgs/Move";
  }

  static const char* value(const ::robot_msgs::Move&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::MoveRequest> should match 
// service_traits::MD5Sum< ::robot_msgs::Move > 
template<>
struct MD5Sum< ::robot_msgs::MoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Move >::value();
  }
  static const char* value(const ::robot_msgs::MoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::MoveRequest> should match 
// service_traits::DataType< ::robot_msgs::Move > 
template<>
struct DataType< ::robot_msgs::MoveRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Move >::value();
  }
  static const char* value(const ::robot_msgs::MoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::MoveResponse> should match 
// service_traits::MD5Sum< ::robot_msgs::Move > 
template<>
struct MD5Sum< ::robot_msgs::MoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Move >::value();
  }
  static const char* value(const ::robot_msgs::MoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::MoveResponse> should match 
// service_traits::DataType< ::robot_msgs::Move > 
template<>
struct DataType< ::robot_msgs::MoveResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Move >::value();
  }
  static const char* value(const ::robot_msgs::MoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_MOVE_H
