// Generated by gencpp from file robot_msgs/RobotMsg.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_ROBOTMSG_H
#define ROBOT_MSGS_MESSAGE_ROBOTMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct RobotMsg_
{
  typedef RobotMsg_<ContainerAllocator> Type;

  RobotMsg_()
    : state(0)
    , mode(0)
    , motor_sync(0)
    , servo_enable(0)  {
    }
  RobotMsg_(const ContainerAllocator& _alloc)
    : state(0)
    , mode(0)
    , motor_sync(0)
    , servo_enable(0)  {
  (void)_alloc;
    }



   typedef int16_t _state_type;
  _state_type state;

   typedef int16_t _mode_type;
  _mode_type mode;

   typedef int16_t _motor_sync_type;
  _motor_sync_type motor_sync;

   typedef int16_t _servo_enable_type;
  _servo_enable_type servo_enable;





  typedef boost::shared_ptr< ::robot_msgs::RobotMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::RobotMsg_<ContainerAllocator> const> ConstPtr;

}; // struct RobotMsg_

typedef ::robot_msgs::RobotMsg_<std::allocator<void> > RobotMsg;

typedef boost::shared_ptr< ::robot_msgs::RobotMsg > RobotMsgPtr;
typedef boost::shared_ptr< ::robot_msgs::RobotMsg const> RobotMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::RobotMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::RobotMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'robot_msgs': ['/home/ylliu/catkin_ws/src/robot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::RobotMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::RobotMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::RobotMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::RobotMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::RobotMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::RobotMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::RobotMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da7d41c000dbbeaf511a5a696db54aea";
  }

  static const char* value(const ::robot_msgs::RobotMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda7d41c000dbbeafULL;
  static const uint64_t static_value2 = 0x511a5a696db54aeaULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::RobotMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/RobotMsg";
  }

  static const char* value(const ::robot_msgs::RobotMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::RobotMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 state\n\
int16 mode\n\
int16 motor_sync\n\
int16 servo_enable\n\
";
  }

  static const char* value(const ::robot_msgs::RobotMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::RobotMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.mode);
      stream.next(m.motor_sync);
      stream.next(m.servo_enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::RobotMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::RobotMsg_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<int16_t>::stream(s, indent + "  ", v.state);
    s << indent << "mode: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mode);
    s << indent << "motor_sync: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motor_sync);
    s << indent << "servo_enable: ";
    Printer<int16_t>::stream(s, indent + "  ", v.servo_enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_ROBOTMSG_H
