// Generated by gencpp from file robot_msgs/SetUserFrame.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_SETUSERFRAME_H
#define ROBOT_MSGS_MESSAGE_SETUSERFRAME_H

#include <ros/service_traits.h>


#include <robot_msgs/SetUserFrameRequest.h>
#include <robot_msgs/SetUserFrameResponse.h>


namespace robot_msgs
{

struct SetUserFrame
{

typedef SetUserFrameRequest Request;
typedef SetUserFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetUserFrame
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::SetUserFrame > {
  static const char* value()
  {
    return "f74c56afc671b9ccd78097ad9fa9b7ce";
  }

  static const char* value(const ::robot_msgs::SetUserFrame&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::SetUserFrame > {
  static const char* value()
  {
    return "robot_msgs/SetUserFrame";
  }

  static const char* value(const ::robot_msgs::SetUserFrame&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::SetUserFrameRequest> should match 
// service_traits::MD5Sum< ::robot_msgs::SetUserFrame > 
template<>
struct MD5Sum< ::robot_msgs::SetUserFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::SetUserFrame >::value();
  }
  static const char* value(const ::robot_msgs::SetUserFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::SetUserFrameRequest> should match 
// service_traits::DataType< ::robot_msgs::SetUserFrame > 
template<>
struct DataType< ::robot_msgs::SetUserFrameRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::SetUserFrame >::value();
  }
  static const char* value(const ::robot_msgs::SetUserFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::SetUserFrameResponse> should match 
// service_traits::MD5Sum< ::robot_msgs::SetUserFrame > 
template<>
struct MD5Sum< ::robot_msgs::SetUserFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::SetUserFrame >::value();
  }
  static const char* value(const ::robot_msgs::SetUserFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::SetUserFrameResponse> should match 
// service_traits::DataType< ::robot_msgs::SetUserFrame > 
template<>
struct DataType< ::robot_msgs::SetUserFrameResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::SetUserFrame >::value();
  }
  static const char* value(const ::robot_msgs::SetUserFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_SETUSERFRAME_H
