(cl:defpackage robot_msgs-srv
  (:use )
  (:export
   "MOVE"
   "<MOVE-REQUEST>"
   "MOVE-REQUEST"
   "<MOVE-RESPONSE>"
   "MOVE-RESPONSE"
   "SETBOOL"
   "<SETBOOL-REQUEST>"
   "SETBOOL-REQUEST"
   "<SETBOOL-RESPONSE>"
   "SETBOOL-RESPONSE"
   "SETTCP"
   "<SETTCP-REQUEST>"
   "SETTCP-REQUEST"
   "<SETTCP-RESPONSE>"
   "SETTCP-RESPONSE"
   "SETUSERFRAME"
   "<SETUSERFRAME-REQUEST>"
   "SETUSERFRAME-REQUEST"
   "<SETUSERFRAME-RESPONSE>"
   "SETUSERFRAME-RESPONSE"
  ))

